name: validation

on:

  push:
    branches: [ main ]
    
  pull_request:
    branches: [ main ]
    
  workflow_dispatch:

jobs:

  build:
  
    runs-on: ubuntu-latest
    container: slacgismo/gridlabd:latest
    
    steps:
    
      - uses: actions/checkout@v2
      
      - name: validate
        run: |
          curl -sL https://raw.githubusercontent.com/openfido/cli/main/install.sh | bash
          sh autotest.sh
        
      - name: artifacts
        uses: actions/upload-artifact@v2
        if: failure()
        with:
          name: autotest-errors
          path: autotest-errors.tar.gz
